"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = true
continuation_prompt = 'â–¶â–¶ '
format = """
[â•­â”€](purple) $os[<](bold red)$shlvl$username$hostname[>](bold red) $battery $memory_usage $all[â•°â”€](purple) $time $directory $character
"""

[battery]
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 100
style = "green"

[character]
success_symbol = "[~>](bold blink green)"
error_symbol = "[âœ—](bold blink red)"

[directory]
truncation_length = 10
truncate_to_repo = true
format = '\[[$path]($style)[$read_only]($read_only_style)\]'

[memory_usage]
symbol = 'ğŸ’¿'
format = "$symbol [${ram_pct}(|${swap_pct})]($style)"
threshold = -1
style = "dimmed bright-cyan"
disabled = false

[os]
format = "[$symbol](purple)"
disabled = false

[shlvl]
disabled = false
threshold = 2
symbol = 'â†•'

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false

[time]
time_format = "%T"
format = "[ğŸ•™ $time]($style)"
style = "#FFA500"
disabled = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@](bold blink purple)[$hostname](bold yellow)'
trim_at = "."
disabled = false
